name: Socialdog Deployment

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: show env file
        run: |
          echo "${{ secrets.ENV_VARS }}"

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_REMOTE_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: ls
