name: Socialdog Deployment

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: copy source via ssh key # ssh key를 이용해 현재 푸시된 소스를 서버에 복사한다.
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /socialdog
        remote_host: ${{ secrets.EC2_REMOTE_IP }}
        remote_user: ${{ secrets.EC2_USERNAME }}
        remote_key: ${{ secrets.EC2_PRIVATE_KEY }}