name: Socialdog Deployment

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - uses: actions/checkout@v2

    - name: install dependencies & build
      run: |
        cd ../
        sudo cp -r socialdog-backend/ /home/ec2-user/socialdog
